### ISSUE TITLE
"pip install katastrophe" does not install docopt automatically

### ISSUE THREAD

**Issue by Tset-Noitamotua** [alyakhtar/Katastrophe#1]
``` shell
...
Successfully built katastrophe tabulate
Installing collected packages: beautifulsoup4, tabulate, requests, lxml, katastrophe
Successfully installed beautifulsoup4-4.4.1 katastrophe-1.0.2 lxml-3.6.0 requests-2.10.0 tabulate-0.7.5

(KATAST~1) C:\Users\User1>katastrophe --version
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\User1\_PYTHO~1\KATAST~1\Scripts\katastrophe.exe\__main__.py", line 5, in <module>
  File "c:\users\user1\_pytho~1\katast~1\lib\site-packages\katastrophe\__init__.py", line 1, in <module>
    from katastrophe import main
  File "c:\users\user1\_pytho~1\katast~1\lib\site-packages\katastrophe\katastrophe.py", line 22, in <module>
    from docopt import docopt
ImportError: No module named docopt
```

**Comment by alyakhtar** [comment]
@Tset-Noitamotua  try by  updating your docopt package.

**Comment by Tset-Noitamotua** [comment]
Sorry, my former issue title was not clear. I meant that docopt is not installed autmatically when installing katastrophe with `pip install katastrophe`. I needed to install it seperatly with `pip install docopt`

**Comment by alyakhtar** [comment]
@Tset-Noitamotua  It should work now.
