### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by el3ctron** [alyakhtar/Katastrophe#12]
when i give a download number to katastrophe software can't download and return this error

Traceback (most recent call last):
  File "/usr/local/bin/katastrophe", line 9, in <module>
    load_entry_point('katastrophe==1.1.9', 'console_scripts', 'katastrophe')()
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 193, in main
    music_torrent()
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/latest.py", line 282, in music_torrent
    download_torrent('https://kat.cr' + torrent_href[(int(serial) + 30) - 1],music[int(serial) - 1][1])
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/latest.py", line 35, in download_torrent
    subprocess.Popen(['xdg-open', mag[torrent - 1]],
NameError: global name 'mag' is not defined

Using Linux Mint 17.1 Rebecca
Release:        17.1
Codename:       rebecca
mint rebeca 17.1 = ubuntu trusty

and Python 2.7.6

**Comment by alyakhtar** [comment]
please update the tool and try again...i have fixed it now.
