### ISSUE TITLE
requests exceptions SSLError while searching

### ISSUE THREAD

**Issue by gowthamsadasivam** [alyakhtar/Katastrophe#14]
Just installed using PIP. When I tried to search it ended up with the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/katastrophe", line 9, in <module>
    load_entry_point('katastrophe==2.0.1', 'console_scripts', 'katastrophe')()
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 235, in main
    table = fetch(query, page)
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 92, in fetch
    source_code = requests.get(link)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Screenshot**:

![katastrophe](https://cloud.githubusercontent.com/assets/5887533/16412669/1f1aa2fe-3d4b-11e6-841f-066cd7d03e6c.jpg)

OS: **Linux - Ubuntu 14.04**
Python: **2.7.6**
PIP: **8.1.2**

**Comment by alyakhtar** [comment]
Try updating your requests package, from what i can figure out the problem lies there.

**Comment by gowthamsadasivam** [comment]
Updated to the latest requests package.

```
$ pip show requests
---
Metadata-Version: 2.0
Name: requests
Version: 2.10.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
```

But still the same issue occurs. Only exception is two new warning lines from urllib3.

```
$ katastrophe      
Torrent Search :  the flash
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/katastrophe", line 9, in <module>
    load_entry_point('katastrophe==2.0.1', 'console_scripts', 'katastrophe')()
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 235, in main
    table = fetch(query, page)
  File "/usr/local/lib/python2.7/dist-packages/katastrophe/katastrophe.py", line 92, in fetch
    source_code = requests.get(link)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Something wrong with the Python version & urllib3 maybe?

**Comment by gowthamsadasivam** [comment]
BTW, quick [search showed](http://stackoverflow.com/a/10668173/2051292) that this is an issue with SSL verification in the requests library. Maybe this is because I'm running behind a proxy server.

As it suggests making the parameter **verify=False** will make this work. While making requests to KAT url don't verify the SSL certificate.

`requests.get('https://example.com', verify=False)`

So making an _optional parameter_ option to disable SSL verification when needed will solve this issue I guess. How about something like this?

`$ katastrophe --verifyssl=False`

**Comment by alyakhtar** [comment]
@gowthamsadasivam  thanks for the suggestion. I have made the changes accordingly. Will work now like this

```
 $katastrophe --verifyssl=false
 $katastrophe --verifyssl=false -m
 $katastrophe --verifyssl=false -T 
```

default option is set to True, hence the following will use SSL connection

```
 $katastrophe 
 $katastrophe -p
```
