### ISSUE TITLE
Can't run Katastrophe

### ISSUE THREAD

**Issue by Integralist** [alyakhtar/Katastrophe#9]
```
$ pip install katastrophe
Collecting katastrophe
  Downloading katastrophe-1.1.3.zip
Collecting beautifulsoup4 (from katastrophe)
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 1.4MB/s 
Collecting tabulate (from katastrophe)
  Downloading tabulate-0.7.5.tar.gz
Collecting requests (from katastrophe)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 507kB 1.0MB/s 
Collecting lxml (from katastrophe)
  Downloading lxml-3.6.0.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 144kB/s 
Collecting docopt (from katastrophe)
  Downloading docopt-0.6.2.tar.gz
Installing collected packages: beautifulsoup4, tabulate, requests, lxml, docopt, katastrophe
  Running setup.py install for tabulate
  Running setup.py install for lxml
  Running setup.py install for docopt
  Running setup.py install for katastrophe
Successfully installed beautifulsoup4-4.4.1 docopt-0.6.2 katastrophe-1.1.3 lxml-3.6.0 requests-2.10.0 tabulate-0.7.5
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Running `katastrophe -h` results in:

```
Traceback (most recent call last):
  File "/Users/M/.pyenv/versions/3.5.1/bin/katastrophe", line 9, in <module>
    load_entry_point('katastrophe==1.1.3', 'console_scripts', 'katastrophe')()
  File "/Users/M/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/M/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Users/M/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Users/M/.pyenv/versions/3.5.1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/M/.pyenv/versions/3.5.1/lib/python3.5/site-packages/katastrophe/__init__.py", line 1, in <module>
    from katastrophe import main
ImportError: cannot import name 'main'
```

> Note: I've downloaded the Vuse Leap client

**Comment by alyakhtar** [comment]
@Integralist you running this on which platform?

**Comment by Integralist** [comment]
@alyakhtar apologies, this is latest Mac OSX. I'm using pyenv for configuring my python setup

**Comment by jerkovicl** [comment]
got the same error on windows 10

```
Traceback (most recent call last):
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Scripts\katastrophe.exe\__main__.py", line 5, in <module>
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\katastrophe\__init__.py", line 1, in <module>
    from katastrophe import main
ImportError: cannot import name 'main'
```

**Comment by alyakhtar** [comment]
hi @Integralist  and @jerkovicl , the problem here is the python version. I have written this is python 2.7 purely, so might give some errors. To fix the problem try changing 

```
from katastrophe import main
```

to 

```
from .katastrophe import main
```

in the **init**.py file

**Comment by jerkovicl** [comment]
@alyakhtar changed the line and got another error

```
Traceback (most recent call last):
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\chocolatey\lib\python3\tools\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Scripts\katastrophe.exe\__main__.py", line 5, in <module>
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\katastrophe\__init__.py", line 1, in <module>
    from .katastrophe import main
  File "c:\programdata\chocolatey\lib\python3\tools\lib\site-packages\katastrophe\katastrophe.py", line 164
    print '\n\nDownload Complete\n'
                                  ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by alyakhtar** [comment]
@jerkovicl as i mentioned before i wrote the code in python 2 so you will have to change print statements everywhere from 

```
print 'print something'
```

to 

```
print('print something')
```
